"""Add cognitive state to conversations table

Revision ID: d465986debb3
Revises: 
Create Date: 2025-12-14 14:03:01.857216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd465986debb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('last_updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('total_conversations', sa.INTEGER(), nullable=False),
    sa.Column('total_messages', sa.BIGINT(), nullable=False),
    sa.Column('emotion_distribution', sa.JSON(), nullable=False),
    sa.Column('sentiment_baseline', sa.JSON(), nullable=False),
    sa.Column('stability_baseline', sa.FLOAT(), nullable=False),
    sa.Column('emotional_transitions', sa.JSON(), nullable=False),
    sa.Column('engagement_index', sa.FLOAT(), nullable=False),
    sa.Column('frustration_index', sa.FLOAT(), nullable=False),
    sa.Column('anomaly_frequency', sa.FLOAT(), nullable=False),
    sa.Column('common_anomaly_types', sa.JSON(), nullable=False),
    sa.Column('profile_confidence', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_emotion_profiles_user_id'), 'emotion_profiles', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=False),
    sa.Column('total_messages', sa.INTEGER(), nullable=False),
    sa.Column('dominant_emotion', sa.String(), nullable=False),
    sa.Column('sentiment_stability', sa.FLOAT(), nullable=False),
    sa.Column('valence_trend', sa.String(), nullable=False),
    sa.Column('emotion_trajectory', sa.JSON(), nullable=False),
    sa.Column('peak_sentiment', sa.JSON(), nullable=False),
    sa.Column('cognitive_state', sa.Enum('mastered', 'exploring', 'struggling', name='cognitivestate'), nullable=False),
    sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_conversations_conversation_id'), 'conversations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.INTEGER(), nullable=False),
    sa.Column('emotion_scores', sa.JSON(), nullable=False),
    sa.Column('primary_emotion', sa.String(), nullable=False),
    sa.Column('valence', sa.FLOAT(), nullable=False),
    sa.Column('arousal', sa.FLOAT(), nullable=False),
    sa.Column('dominance', sa.FLOAT(), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), nullable=False),
    sa.Column('analysis_model', sa.String(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('anomalies',
    sa.Column('detection_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_type', sa.Enum('Sentiment_Shift', 'Sustained_Negativity', 'High_Intensity_Distress', 'State_Deviation', name='anomalytype'), nullable=False),
    sa.Column('anomaly_score', sa.FLOAT(), nullable=False),
    sa.Column('severity_level', sa.Enum('low', 'medium', 'high', 'critical', name='severitylevel'), nullable=False),
    sa.Column('status', sa.Enum('unhandled', 'recorded', 'notified', name='anomalystatus'), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('detection_id')
    )
    op.create_index(op.f('ix_anomalies_conversation_id'), 'anomalies', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_anomalies_detection_id'), 'anomalies', ['detection_id'], unique=False)
    op.create_index(op.f('ix_anomalies_user_id'), 'anomalies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomalies_user_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_detection_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_conversation_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_conversation_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_emotion_profiles_user_id'), table_name='emotion_profiles')
    op.drop_table('emotion_profiles')
    # ### end Alembic commands ###
